apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-ingress-deployment
spec:
  selector:
    matchLabels:
      app: argocd-ingress
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 50%
  template:
    metadata: 
      labels:
        app: argocd-ingress
        app.kubernetes.io/name: argocd-ingress
    spec:
      containers:
      - name: testapp
        image: sysose/argocd-ingress:1.0
        resources:
          requests:
            memory: "32Mi"
            cpu: "50m"
          limits:
            memory: "32Mi"
            cpu: "50m"
        ports:
        - containerPort: 5000
        livenessProbe:
          httpGet:
            path: /
            port: 5000
          initialDelaySeconds: 5
          periodSeconds: 5
        readynessProbe:
          httpGet:
            path: /
            port: 5000
            initialDelaySeconds: 5
            periodSeconds: 5